export const ERROR_CODES = {
  TRIP_CALCULATE_ERROR: 'TRIP_CALCULATE_ERROR',
  DESTINATION_CREATE_ERROR: 'DESTINATION_CREATE_ERROR',
  DESTINATION_LIST_GET_DESTINATIONS_ERROR: 'DESTINATION_LIST_GET_DESTINATIONS_ERROR',
} as const

export type ErrorCode = keyof typeof ERROR_CODES
