export const ERROR_CODES = {
  DESTINATIONS_NOT_FOUND: 'DESTINATIONS_NOT_FOUND',
  DESTINATION_DUPLICATED_NAME: 'DESTINATION_DUPLICATED_NAME',
  DESTINATION_CREATE: 'DESTINATION_CREATE',
  DESTINATION_DELETE_MISSING_ID: 'DESTINATION_DELETE_MISSING_ID',
  DESTINATION_DELETE: 'DESTINATION_DELETE',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
